### ISSUE TITLE
can't search by  the  second-dimensional key

### ISSUE THREAD

**Issue by minping111111** [taomin597715379/redisvo#3]
![image](https://user-images.githubusercontent.com/9964047/29152958-10e09bae-7dbd-11e7-921a-6d41b0c974d2.png)
see the screenshot above, when the first-dimensional key named 'svr_system_config' has too many second-dimensional key，how can i find the special  second-dimensional key named 'client_deploy_setting' quickly?can it support search by the second-dimensional key ?

**Comment by taomin597715379** [comment]
It's my pleasure that this redis tool can serve for you. I've seen your question and have begun to add this feature
